[DEFAULT]
VENV = /opt/argo-connectors/

[CUSTOMER_SAMPLE]
Name = SAMPLE
OutputDir = %(VENV)s/var/lib/argo-connectors/SAMPLE/
Jobs = Critical
AuthenticationUsePlainHttpAuth = False
AuthenticationHttpUser = http_user
AuthenticationHttpPass = secret_pass
ServiceTypesFeed =
TopoFeed = https://goc.egi.eu/
TopoFeedPaging = False
TopoFeedServiceEndpoints =
TopoFeedServiceEndpointsExtensions =
TopoFeedServiceGroups =
TopoFeedSites =
TopoFetchType = Sites, ServiceGroups
TopoScope =
HonorNotificationFlag = False
TopoType = GOCDB
WeightsEmpty = False
DowntimesEmpty = False
BDII = False
BDIIHost = bdii.egi.cro-ngi.hr
BDIIPort = 2170
BDIIQueryBase = o=grid
BDIIQueryFilterSRM = (&(objectClass=GlueService)(|(GlueServiceType=srm_v1)(GlueServiceType=srm)))
BDIIQueryAttributesSRM = GlueServiceEndpoint
BDIIQueryFilterSEPATH = (objectClass=GlueSATop)
BDIIQueryAttributesSEPATH = GlueVOInfoAccessControlBaseRule GlueVOInfoPath

[Critical]
Dirname = EGI_Critical
Profiles = ARGO_MON_CRITICAL
MetricProfileNamespace = ch.cern.SAM
